### ISSUE TITLE
Current summary of items to fix for ww2.13 release 

### ISSUE THREAD

**Issue by mgage** [openwebwork/webwork2#776]
To fix for ww2.13:
pg PR

- [x] #302 multianswer fix @done(2017-06-21)
- [x]  #290 perl warnings   bidewolf
- [x]  #284 PGmatrixmacros and "cellspacing" (replaced by #303) 
- [x]  #303 updated PGmatrixmacros and "cellspacing"
webwork2 PR
- [ ]  postponed for now until decision is made on desired behavior of gateway tests.  #740 gateway answer bug #740 -- needs documentation as much as anything -- .
- [x] #744 codemirror updates #744 -- adds line wrapping -- minor @done(2017-06-21)
- [x]  #745 specific charset on new OPL tables #745 bldewolf -- will take some checking -- replaced by #778 which resolves immediate issue without implementing full utf8 compliance
- [x] #748 sanitize scoring download  getfile parameter -- fixes #3793 mgage @done(2017-06-21)
- [x]  #749  scoring download bug fix for master.  mgage -- needs updating
- [x]  #767 multianswer fix -- fixes multiAnswer bugs. @done(2017-06-21)
- [x] include pastanswer fix @done(2017-06-21)
- [x]   #766 typo @done(2017-06-21)
- [x]   #775 Configure URLs for PGProblemEditor help buttons in default.conf @done(2017-06-21)
- [x]    #778 fixes immediate issue of OPL-update in #745 
- [x]    #774 improves filename filtering for scoring download (originally addressed in #748)
- [x]    #760 and #761  easy maketext additions
- [x]   #771 (merged)Additional tweaks to Email::Sender should be addressed to  make setup easier and to determine what fields need to be filled out to prevent spam alerts, etc. Also compare the error alerts of the Feedback page and of the SendMail page -- the Feedback page alerts seem to be better?
- [x]  #779 Security fix of SQL injection.  
- [ ]  #780 Another round of Email::Sender fixes.  

Suggest other easily resolved issues and bugs to include in the 2.13 release.

**Comment by pstaabp** [comment]
@mgage If you'd like to assign some of these to me, I'd be happy to take a look.

**Comment by mgage** [comment]
Could you look at #290 an #284 in pg?  Make sure the PR starts from the develop branch.

Could someone who uses Gateway quizzes regularly look at #740?  I think the issues are largely fixed but we need better documentation on Gateway quizzes to try to reduce the number of times the same questions are asked about the Gateway quiz options.
